language: node_js
node_js:
- '6'
script:
- npm run test
- npm run build
#notifications:
#  slack: ghimplementationteam:P8HpTjSCo8cDGwahXPLgQh47
cache:
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: build
  skip_cleanup: true
  on:
    repo: GHImplementationTeam/FrontEnd
    all_branches: true
  bucket: cemaritan-deployments
