swagger: '2.0'

info:
  version: "0.1.0"
  title: Cemaritan API

host: app.cemaritan.com
basePath: /api

schemes:
  - https

paths:
  /users/:
    get:
      description: |
        Gets `User` objects.
        Optional query param of **limit** determines
        number of returned users
      parameters:
        -
          name: limit
          in: query
          description: Number of Users
          required: false
          type: number
          format: int
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfUsers
            type: array
            items:
              title: User
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean