swagger: '2.0'

info:
  version: "0.1.0"
  title: Cemaritan API

host: app.cemaritan.com
basePath: /api

schemes:
  - https

paths:
  /employees/:
    get:
      description: |
        Gets `Employee` objects.
        Optional query param of **limit** determines
        number of returned employees
      parameters:
        -
          name: limit
          in: query
          description: Number of Employees
          required: false
          type: number
          format: int
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfEmployees
            type: array
            items:
              title: Employee
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean